version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FinanceManagementDb;User Id=sa;Password=YourStrong!Passw0rd;

  db:
    build:
      context: .
      dockerfile: Backend/Dockerfile.db
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./Backend/Database/Scripts:/var/opt/mssql/scripts